### ISSUE TITLE
Error: Cannot find module denpendency

### ISSUE THREAD

**Issue by wuwb** [krakenjs/confit#63]
``` shell
Error: Cannot find module '.........../node_modules/confit/dist/lib/base.js'
at Function.Module._resolveFilename (module.js:455:15)
    at Function.resolve (internal/module.js:27:19)
    at shush (/Users/eqielb/Development/mogujie/Groups/xmen/xmen/node_modules/confit/node_modules/shush/index.js:27:19)
    at Factory._resolveFile (/Users/eqielb/Development/mogujie/Groups/xmen/xmen/node_modules/confit/dist/lib/factory.js:125:28)
    at Factory._add (/Users/eqielb/Development/mogujie/Groups/xmen/xmen/node_modules/confit/dist/lib/factory.js:112:33)
    at Factory.addDefault (/Users/eqielb/Development/mogujie/Groups/xmen/xmen/node_modules/confit/dist/lib/factory.js:81:22)
    at Object.<anonymous> (/Users/eqielb/Development/mogujie/Groups/xmen/xmen/src/config/index.js:16:6)
    at Module._compile (module.js:556:32)
    at loader (/Users/eqielb/Development/mogujie/Groups/xmen/xmen/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/eqielb/Development/mogujie/Groups/xmen/xmen/node_modules/babel-register/lib/node.js:154:7)
```

**Comment by shaunwarman** [comment]
Hey @aiwb 

Do you have a sample config or repo of how you are using confit?

**Comment by grawk** [comment]
closing due to inactivity. Feel free to re-open if providing details to reproduce.
